# Практические задачи: Numpy и Pandas

## Задача 1. Детектор хайпа (Pandas)

In [5]:
import pandas as pd
import numpy as np

# Генерация данных (как в условии)
np.random.seed(42)
data = {
    'video_id': [f'V{i:03d}' for i in range(1, 21)],
    'views_start': np.random.randint(1000, 10000, 20),
    'views_end': np.random.randint(3000, 50000, 20),
    'category': np.random.choice(['Юмор', 'IT', 'Еда'], 20)
}
df = pd.DataFrame(data)

#1. Рассчитать колонку growth_rate — процент роста просмотров за день
df['growth_rate'] = ((df['views_end'] - df['views_start']) / df['views_start']) * 100

#2. Отфильтровать видео с ростом более 200%
hype_videos = df[df['growth_rate'] > 200].sort_values(by='growth_rate', ascending=False)

#3. Подсчитать количество хайповых видео по категориям
category_hype_count = hype_videos['category'].value_counts().reset_index()
category_hype_count.columns = ['category', 'hype_count']

#4. Вывести ТОП-3 самых быстрорастущих видео
top_3 = df.nlargest(3, 'growth_rate')[['video_id', 'growth_rate']]


print("Рост просмотров")
print(df[['video_id', 'views_start', 'views_end', 'growth_rate']].round(1))

print("\nХайповые видео (>200%)")
print(hype_videos[['video_id', 'category', 'growth_rate']].round(1))

print("\nКоличество хайповых видео по категориям")
print(category_hype_count)

print("\nТОП-3 самых быстрорастущих видео")
print(top_3)

Рост просмотров
   video_id  views_start  views_end  growth_rate
0      V001         8270      31693        283.2
1      V002         1860       9396        405.2
2      V003         6390      30480        377.0
3      V004         6191      44434        617.7
4      V005         6734      28658        325.6
5      V006         7265      21942        202.0
6      V007         1466      21431       1361.9
7      V008         5426       5747          5.9
8      V009         6578       3189        -51.5
9      V010         9322      22118        137.3
10     V011         2685      38773       1344.1
11     V012         1769       4899        176.9
12     V013         7949       4267        -46.3
13     V014         3433      34551        906.4
14     V015         6311      14394        128.1
15     V016         6051       6556          8.3
16     V017         7420       6890         -7.1
17     V018         2184      44606       1942.4
18     V019         5555      33740        507.4
19  

## Задача 2. Зрение беспилотника (Numpy)


In [ ]:
import numpy as np

# 1. Создать массив 20×20 из нулей (пустая дорога)
road = np.zeros((20, 20))

# 2. Заполнить средний столбец (индекс 10) единицами (разметка)
road[:, 10] = 1

# 3. Сдвинуть все единицы на 2 позиции влево (поворот)
road[:, 8] = road[:, 10]
road[:, 10] = 0

# 4. Делаем разметку прерывистой: обнуляем каждую вторую единицу
road[1::2, 8] = 0


print(road[:, 8])

Итоговая разметка (столбец 8):
[1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]


## Задача 3. ИИ-фильтр плохих слов (Pandas + Текст)

In [ ]:
import pandas as pd


messages = [
"Привет всем участникам чата",
"Розыгрыш iPhone прямо сейчас!!!",
"Кто знает хороший курс по Python?",
"@admin помогите разобраться",
"КРИПТА только растет #bitcoin $$$",
"Отличная статья про машинное обучение",
"Розыгрыш* призов каждый день",
"Подскажите книгу для начинающих",
"Заработок на крипте легко",
"Спасибо за помощь",
"### Супер предложение ###",
"Изучаю pandas для анализа данных",
"Розыгрыш 1000$ для всех",
"Какой фреймворк выбрать для веба?",
"Крипта это будущее финансов",
]
df = pd.DataFrame({'message': messages})

# 1. Найти сообщения со словами "крипта" или "розыгрыш" (регистронезависимо), пометить как is_spam = True
df['is_spam'] = df['message'].str.contains('крипта|розыгрыш', case=False, regex=True)

# 2. Удалить спецсимволы @ , # , $ , * с помощью регулярных выражений
df['cleaned_message'] = df['message'].str.replace('[@#$*]', '', regex=True)

# 3. Создать колонку word_count с количеством слов в сообщении
df['word_count'] = df['cleaned_message'].str.split().str.len()

# 4. Оставить только сообщения с более чем 3 словами, которые не являются спамом
result = df[(df['is_spam'] == False) & (df['word_count'] > 3)]


print(result[['message', 'is_spam', 'word_count']].reset_index(drop=True))

===== Итоговые данные =====
                                 message  is_spam  word_count
0            Привет всем участникам чата    False           4
1      Кто знает хороший курс по Python?    False           6
2  Отличная статья про машинное обучение    False           5
3        Подскажите книгу для начинающих    False           4
4              Заработок на крипте легко    False           4
5       Изучаю pandas для анализа данных    False           5
6      Какой фреймворк выбрать для веба?    False           5


## Задача 4. Генератор лиц (Numpy)

In [54]:
import numpy as np

# 1. Создать тензор размером 10×64×64×3 (10 RGB изображений 64×64)
#2. Заполнить случайными числами из нормального распределения (μ=0, σ=1)
images = np.random.normal(loc=0.0, scale=1.0, size=(10, 64, 64, 3))


random_idx = 3
# 3. Выбрать одно случайное изображение и заполнить каждый 4-й ряд красным цветом [255, 0, 0]

images[random_idx, ::4, :, :] = [255, 0, 0]  # ::4 — каждая 4-я строка

# 4. Создать "среднее изображение" размером 64×64×3 как среднее арифметическое всех 10 изображений
mean_image = np.mean(images, axis=0)  


print("Размер тензора images:", images.shape)         
print("Размер mean_image:", mean_image.shape)         
print("Значение в строке 0, столбце 0, канал R (красный):", mean_image[0, 0, 0])


Размер тензора images: (10, 64, 64, 3)
Размер mean_image: (64, 64, 3)
Значение в строке 0, столбце 0, канал R (красный): 25.651697283483134


## Задача 5. Система рекомендаций (Pandas + Numpy)

In [ ]:
import pandas as pd
import numpy as np


np.random.seed(42)
users = [f'User_{i}' for i in range(1, 11)]
genres = ['Рок', 'Поп', 'Техно', 'Рэп']
data = np.random.randint(0, 100, size=(10, 4))
df = pd.DataFrame(data, columns=genres, index=users)

# 1. Преобразовать DataFrame в матрицу Numpy
matrix = df.to_numpy()

# 2. Нормировать данные: для каждого пользователя сумма прослушиваний по всем жанрам должна равняться 1
row_sums = matrix.sum(axis=1, keepdims=True)  # Суммы по строкам 
normalized_matrix = matrix / row_sums  

# 3. Вычислить расстояние между первым пользователем и всеми остальными (евклидово расстояние)
first_user = normalized_matrix[0]  
distances = np.sqrt(np.sum((normalized_matrix - first_user) ** 2, axis=1))  # Евклидово расстояние

# 4. Найти ID пользователя с максимально похожими предпочтениями (минимальное расстояние, но не сам пользователь)
distances[0] = np.inf  
most_similar_idx = np.argmin(distances)  
most_similar_user = users[most_similar_idx]  # ID пользователя
distance_to_most_similar_user = distances[most_similar_idx]

print(df)

print("\nНормированная матрица")
print(normalized_matrix.round(3))

print("\nРасстояния до первого пользователя")
for user, dist in zip(users, distances):
    print(f"{user}: {dist:.3f}")

print("\nПользователь с наиболее похожими предпочтениями и расстояние до него")
print(f"{most_similar_user} и расстояние до него = {distance_to_most_similar_user:.7f}")

         Рок  Поп  Техно  Рэп
User_1    51   92     14   71
User_2    60   20     82   86
User_3    74   74     87   99
User_4    23    2     21   52
User_5     1   87     29   37
User_6     1   63     59   20
User_7    32   75     57   21
User_8    88   48     90   58
User_9    41   91     59   79
User_10   14   61     61   46

Нормированная матрица
[[0.224 0.404 0.061 0.311]
 [0.242 0.081 0.331 0.347]
 [0.222 0.222 0.26  0.296]
 [0.235 0.02  0.214 0.531]
 [0.006 0.565 0.188 0.24 ]
 [0.007 0.441 0.413 0.14 ]
 [0.173 0.405 0.308 0.114]
 [0.31  0.169 0.317 0.204]
 [0.152 0.337 0.219 0.293]
 [0.077 0.335 0.335 0.253]]

Расстояния до первого пользователя
User_1: inf
User_2: 0.422
User_3: 0.270
User_4: 0.467
User_5: 0.307
User_6: 0.448
User_7: 0.320
User_8: 0.373
User_9: 0.186
User_10: 0.323

Пользователь с наиболее похожими предпочтениями и расстояние до него
User_9 и  расстояние до него = 0.1860574


Рок      41
Поп      91
Техно    59
Рэп      79
Name: User_9, dtype: int32

8